---
apiVersion: v1
kind: Service
metadata:
  name: productbrochure
  labels:
    app: productbrochure
spec:
  type: NodePort
  selector:
    app: productbrochure
  ports:
  - protocol: TCP
    port: 8020
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productbrochure
spec:
  selector:
    matchLabels:
      app: productbrochure
  replicas: 1
  template:
    metadata:
      labels:
        app: productbrochure
    spec:
      containers:
      - name: productbrochure
        image: praveenr4u/productbrochure:latest
        ports:
        - containerPort: 8020
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8025
          initialDelaySeconds: 30
          timeoutSeconds: 1
