---
apiVersion: v1
kind: Service
metadata:
  name: showroom
  labels:
    app: showroom
spec:
  type: NodePort
  selector:
    app: showroom
  ports:
  - protocol: TCP
    port: 8010
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: showroom
spec:
  selector:
    matchLabels:
      app: showroom
  replicas: 1
  template:
    metadata:
      labels:
        app: showroom
    spec:
      containers:
      - name: showroom
        image: praveenr4u/showroom:latest
        ports:
        - containerPort: 8010
        livenessProbe:
          httpGet:
            path: /health
            port: 8010
          initialDelaySeconds: 30
          timeoutSeconds: 1
